export const ADD_TODO = "ADD_TODO";
export const TOGGLE_COMPLETE = "TOGGLE_COMPLETE";
export const DELETE_TODO = "DELETE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const CLEAR_INPUT_FIELD = "CLEAR_INPUT_FIELD";
export const COMPLETED_TODO = "COMPLETED_TODO";
